# Generated by Django 6.1 on 2026-08-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_initial'),
        ('pedagogie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_generation', models.CharField(choices=[('IA', 'Généré par IA'), ('MANUEL', 'Créé par un mentor/professeur')], max_length=10)),
                ('date_publication', models.DateTimeField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='pedagogie.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField()),
                ('type_question', models.CharField(choices=[('QCM', 'Choix multiple'), ('LIBRE', 'Réponse libre')], default='QCM', max_length=10)),
                ('notion', models.CharField(help_text="Notion/thème précis (ex: 'Équations du second degré') pour le diagnostic fin.", max_length=150)),
                ('choix_reponses', models.JSONField(blank=True, help_text='Liste des choix si QCM.', null=True)),
                ('bonne_reponse', models.CharField(max_length=500)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.examen')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_donnee', models.CharField(max_length=500)),
                ('correct', models.BooleanField()),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='comptes.eleve')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evaluations.question')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_passage', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='comptes.eleve')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='evaluations.examen')),
            ],
            options={
                'unique_together': {('eleve', 'examen')},
            },
        ),
    ]
