# Generated by Django 6.1 on 2026-08-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_examen_date_validation_examen_professeur_validateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='niveau_difficulte',
            field=models.CharField(choices=[('FACILE', 'Facile'), ('MOYEN', 'Moyen'), ('DIFFICILE', 'Difficile')], default='MOYEN', max_length=10),
        ),
    ]
