# Generated by Django 6.1 on 2026-08-21 05:42

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_examen_niveau_difficulte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='enonce',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
