# Generated by Django 6.1 on 2026-08-13 14:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('note_evaluation', models.PositiveSmallIntegerField(blank=True, help_text="Note de 1 à 5 donnée par l'élève pour cette matière précise.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('classe_scolaire', models.CharField(choices=[('6EME', 'Sixième'), ('5EME', 'Cinquième'), ('4EME', 'Quatrième'), ('3EME', 'Troisième'), ('2ND', 'Seconde'), ('1ERE', 'Première'), ('TLE', 'Terminale')], max_length=10)),
                ('serie', models.CharField(choices=[('AUCUNE', 'Aucune (collège)'), ('A', 'Série A'), ('B', 'Série B'), ('C', 'Série C'), ('D', 'Série D')], default='AUCUNE', max_length=10)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_eleve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
