# Generated by Django 6.1 on 2026-08-15 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_initial'),
        ('evaluations', '0001_initial'),
        ('pedagogie', '0002_sequence_delete_progression'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_maitrise', models.DecimalField(decimal_places=2, default=0, help_text='Score de maîtrise global sur cette matière (0 à 100).', max_digits=5)),
                ('notions_faibles', models.JSONField(blank=True, default=list, help_text="Liste des notions où l'élève est en difficulté (calculé depuis ReponseEleve).")),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='comptes.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='pedagogie.matiere')),
            ],
            options={
                'unique_together': {('eleve', 'matiere')},
            },
        ),
    ]
