# Generated by Django 6.1 on 2026-08-13 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('classe_scolaire', models.CharField(choices=[('6EME', 'Sixième'), ('5EME', 'Cinquième'), ('4EME', 'Quatrième'), ('3EME', 'Troisième'), ('2ND', 'Seconde'), ('1ERE', 'Première'), ('TLE', 'Terminale')], max_length=10)),
                ('serie', models.CharField(choices=[('AUCUNE', 'Aucune (collège)'), ('A', 'Série A'), ('B', 'Série B'), ('C', 'Série C'), ('D', 'Série D')], default='AUCUNE', max_length=10)),
                ('contenu', models.TextField(help_text="Contenu du cours généré par l'IA.")),
                ('source_manuel', models.CharField(blank=True, help_text='Référence du manuel officiel source.', max_length=255)),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('professeur_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_valides', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='pedagogie.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='CoefficientMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(choices=[('AUCUNE', 'Aucune (collège)'), ('A', 'Série A'), ('B', 'Série B'), ('C', 'Série C'), ('D', 'Série D')], max_length=10)),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='pedagogie.matiere')),
            ],
            options={
                'unique_together': {('matiere', 'serie')},
            },
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_maitrise', models.DecimalField(decimal_places=2, default=0, help_text='Score de maîtrise global sur cette matière (0 à 100).', max_digits=5)),
                ('notions_faibles', models.JSONField(blank=True, default=list, help_text="Liste des notions où l'élève est en difficulté (calculé depuis ReponseEleve).")),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='comptes.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='pedagogie.matiere')),
            ],
            options={
                'unique_together': {('eleve', 'matiere')},
            },
        ),
    ]
