# Generated by Django 6.1 on 2026-08-18 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_initial'),
        ('pedagogie', '0002_sequence_delete_progression'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursTermine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completion', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termine_par', to='pedagogie.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_termines', to='comptes.eleve')),
            ],
            options={
                'unique_together': {('eleve', 'cours')},
            },
        ),
    ]
