# Generated by Django 6.1 on 2026-08-13 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedagogie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotInterdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('classe_scolaire', models.CharField(choices=[('6EME', 'Sixième'), ('5EME', 'Cinquième'), ('4EME', 'Quatrième'), ('3EME', 'Troisième'), ('2ND', 'Seconde'), ('1ERE', 'Première'), ('TLE', 'Terminale')], max_length=10)),
                ('serie', models.CharField(choices=[('AUCUNE', 'Aucune (collège)'), ('A', 'Série A'), ('B', 'Série B'), ('C', 'Série C'), ('D', 'Série D')], default='AUCUNE', max_length=10)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_etude', to='pedagogie.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('VISIBLE', 'Visible'), ('MASQUE', 'Masqué'), ('SIGNALE', 'Signalé'), ('EN_ATTENTE', 'En attente de révision')], default='VISIBLE', max_length=10)),
                ('traite_par_ia', models.BooleanField(default=False)),
                ('score_risque', models.DecimalField(blank=True, decimal_places=2, help_text="Score de risque (0 à 1) donné par l'IA de modération.", max_digits=3, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communaute.groupeetude')),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=255)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='communaute.message')),
                ('signale_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_effectues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
