# Generated by Django 6.1 on 2026-08-15 01:38

import django_ckeditor_5.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(help_text='Position de la séquence dans le cours (1, 2, 3...).')),
                ('contenu', django_ckeditor_5.fields.CKEditor5Field()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='pedagogie.cours')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.DeleteModel(
            name='Progression',
        ),
    ]
