# Generated by Django 6.1 on 2026-08-15 01:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communaute', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signalement',
            unique_together={('message', 'signale_par')},
        ),
    ]
