# Generated by Django 6.1 on 2026-08-15 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communaute', '0002_alter_signalement_unique_together'),
        ('comptes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('VISIBLE', 'Visible'), ('MASQUE', 'Masqué'), ('EN_ATTENTE', 'En attente de révision')], default='VISIBLE', max_length=10)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_prives_envoyes', to=settings.AUTH_USER_MODEL)),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_prives', to='comptes.suivimentor')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
    ]
