# Generated by Django 6.1 on 2026-08-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communaute', '0005_mettre_a_valide_groupes_existants'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageprive',
            name='lu',
            field=models.BooleanField(default=False, help_text='Lu par le destinataire.'),
        ),
    ]
