"""
Django settings for Evoly project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# If python-dotenv is installed, load environment variables from a local
# .env file so `os.environ` contains keys defined there. This is optional
# and harmless when python-dotenv is not available.
try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read the secret key from environment variables. Support both
# `DJANGO_SECRET_KEY` and `SECRET_KEY` names, and fall back to the
# previous literal value if none is set (useful for local development).
SECRET_KEY = (
    os.environ.get('DJANGO_SECRET_KEY')
    or os.environ.get('SECRET_KEY')
)

# SECURITY WARNING: don't run with debug turned on in production!
# Lu depuis l'env (DEBUG=False sur Render via render.yaml).
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

def _liste_env(nom):
    return [h.strip() for h in os.environ.get(nom, '').split(',') if h.strip()]

if os.environ.get('DJANGO_ALLOWED_HOSTS'):
    ALLOWED_HOSTS = _liste_env('DJANGO_ALLOWED_HOSTS')
elif DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = []

# Domaine(s) Vercel / Render autorisés en prod, lus depuis l'env
# (ex: CORS_ALLOWED_ORIGINS=https://evoly.vercel.app,https://evoly-api.onrender.com)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
] + _liste_env('CORS_ALLOWED_ORIGINS')
CSRF_TRUSTED_ORIGINS = _liste_env('CSRF_TRUSTED_ORIGINS')

CSRF_COOKIE_HTTPONLY = True

# Derrière le proxy HTTPS de Render, il faut lui faire confiance pour
# détecter le schéma https (redirections, CSRF, cookies sécurisés).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_ckeditor_5',
    'comptes',
    'dashboard',
    'abonnements',
    'pedagogie',
    'evaluations',
    'communaute',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'evoly.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'evoly.wsgi.application'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'

# Static files locations (project-level `static/` directory)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Destination de collectstatic en production (servi par WhiteNoise)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------
# Stockage des fichiers
#
# - staticfiles : servi par WhiteNoise (compressé) en production.
# - default (médias uploadés : images CKEditor des cours…) :
#   * Supabase Storage (backend S3 de django-storages) dès que les
#     variables AWS_S3_ENDPOINT_URL / AWS_STORAGE_BUCKET_NAME sont
#     définies — INDISPENSABLE sur Render dont le disque est éphémère,
#     sinon les fichiers uploadés sont perdus à chaque redéploiement.
#   * système de fichiers local sinon (développement).
# ---------------------------------------------------------------

if os.environ.get('AWS_S3_ENDPOINT_URL') and os.environ.get('AWS_STORAGE_BUCKET_NAME'):
    STORAGES = {
        'default': {'BACKEND': 'storages.backends.s3.S3Storage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
    }

    # Compatibilité S3 de Supabase Storage (valeurs issues du dashboard
    # Supabase → Settings → Storage ; JAMAIS en dur ici).
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'eu-west-3')

    # Style d'adressage « path » requis par Supabase (<endpoint>/<bucket>/<clé>)
    AWS_S3_ADDRESSING_STYLE = 'path'
    # Bucket public : URLs directes sans signature (?X-Amz-…)
    AWS_QUERYSTRING_AUTH = False
    # Ne pas écraser un fichier existant : clé unique à chaque upload
    AWS_S3_FILE_OVERWRITE = False
else:
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
    }

# CKEditor 5
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link',
            'bulletedList', 'numberedList', 'blockQuote',
            'imageUpload', 'insertTable', 'codeBlock',
            'sourceEditing',
        ],
        'language': 'fr',
    },
    'contenu_interactif': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link',
            'bulletedList', 'numberedList', 'blockQuote',
            'imageUpload', 'insertTable', 'codeBlock',
            'htmlEmbed', 'sourceEditing',
        ],
        'htmlSupport': {
            'allow': [
                {
                    'name': 'script',
                    'attributes': True,
                    'classes': True,
                    'styles': True,
                },
                {
                    'name': 'iframe',
                    'attributes': True,
                    'classes': True,
                    'styles': True,
                },
                {
                    'name': 'canvas',
                    'attributes': True,
                    'classes': True,
                    'styles': True,
                },
            ],
        },
    },
}


COHERE_API_KEY = os.environ.get("COHERE_API_KEY")

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# PostgreSQL par défaut (variables lues depuis .env : DB_NAME, DB_USER,
# DB_PASSWORD, DB_HOST, DB_PORT). Pour revenir à SQLite en développement
# local, définir DB_ENGINE='django.db.backends.sqlite3' dans .env.
if os.environ.get('DB_ENGINE') == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }

    # En production, échouer explicitement si la base n'est pas configurée
    # plutôt que de tenter localhost et planter avec une erreur obscure.
    if not DEBUG:
        _manquantes = [
            v for v in ('DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_HOST')
            if not os.environ.get(v)
        ]
        if _manquantes:
            from django.core.exceptions import ImproperlyConfigured
            raise ImproperlyConfigured(
                f"Variables d'environnement manquantes : {', '.join(_manquantes)}. "
                "Renseignez-les dans le dashboard Render (base Supabase)."
            )


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Django REST framework + CORS settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

CORS_ALLOW_CREDENTIALS = True
