# Generated by Django 6.1 on 2026-08-13 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('pedagogie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='matieres',
            field=models.ManyToManyField(related_name='mentors', to='pedagogie.matiere'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suivimentor',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_mentors', to='comptes.eleve'),
        ),
        migrations.AddField(
            model_name='suivimentor',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.matiere'),
        ),
        migrations.AddField(
            model_name='suivimentor',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='comptes.mentor'),
        ),
    ]
